default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      args: [--line-length=120]
      exclude: ^modules/
-   repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: ^modules/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
    - id: mypy
